[package]
name = "adder"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
add-one = { path = "../add-one" } # Cargo默认同workspace间的crates没有关联，因此使用需要显式定义
rand = "0.8.3"