[package]
name = "chip_examples"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
halo2_proofs = { path = "../../../../../github.com/zcash/halo2/halo2_proofs", version = "0.1.0-beta.1" }